config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pics do
    member do
      put "like", to: "pics#upvote"
    end
  end


  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    acts_as_votable
    belongs_to :user

    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

   
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    add_flash_types :danger, :info, :warning, :success
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :find_pic, only: [:edit, :update, :show, :destroy, :upvote]

    before_action :authenticate_user!, except: [:index, :show]

    def index
        @pics = Pic.all
    end

    def show
    end

    def new
        @pic = Pic.new
    end

    def create
        @pic = current_user.pics.new(pic_params)
        respond_to do |format|
            if @pic.save
              format.html { redirect_to @pic, warning: 'Pic Creada Exitosamente.' }
              format.json { render :show, status: :created, location: @pic }
            else
              format.html { render :new }
              format.json { render json: @pic.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
    end

     def update
        respond_to do |format|
            if @pic.update(pic_params)
              format.html { redirect_to @pic, warning: 'Pic Editada Exitosamente.' }
              format.json { render :show, status: :ok, location: @pic }
            else
              format.html { render :edit }
              format.json { render json: @pic.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @pic.destroy
            respond_to do |format|
                format.html { redirect_to pics_url, warning: 'Pic Borrado Exitosamente.' }
                format.json { head :no_content }
        end
    end

    def upvote
        @pic.upvote_by current_user
        redirect_to @pic
    end

    def find_pic
        @pic = Pic.find(params[:id])
    end

    private
        def pic_params
            params.require(:pic).permit(:title, :description, :image)
        end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar"%>
    <div class="container">
      <%= render "partials/notificaciones" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark text-white">
      <div class="navbar-brand"><%= link_to "Instagram Rails", root_path%></div>
        <% if user_signed_in? %>
          <div class="navbar-nav ml-auto">
            <div class="nav-item nav-link"><%= link_to "Postea", new_pic_path %></div>
            <div class="nav-item nav-link"><%= link_to "Configuracion", edit_user_registration_path %></div>
            <div class="nav-item nav-link"><%= link_to "Desloguearse", destroy_user_session_path, method: :delete %></div>
          </div>
        <% else %>
          <div class="navbar-nav ml-auto">
            <div class="nav-item nav-link"><%= link_to "Unete", new_user_registration_path %></div>
            <div class="nav-item nav-link"><%= link_to "Inicia Sesion", new_user_session_path %></div>
          </div>
        <% end %>
    </nav>

app/views/partials/_notificaciones.html.erb
<% flash.each do |name, msg| %>
        <div class="alert alert-dismissible alert-<%= name %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4 class="alert-heading"><%= msg %></h4>
        </div>
      <%end%>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: {multipart: true} do |f| %>
    <% if @pic.errors.any? %>
            <div id="errors">
                <h2><%= pluralize(@pic.errors.count, "error")%> Pic No Puede Ser Guardada</h2>
                <ul>
                    <% @pic.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
    <div class="form-group">
        <%= f.input :image, input_html: { class: 'form-control'} %>
    </div>
    <div class="form-group">
        <%= f.input :title, input_html: { class: 'form-control'} %>
    </div>
    <div class="form-group">
        <%= f.input :description, input_html: { class: 'form-control'} %>
    </div>
        <%= f.button :submit, class: "btn btn-info"%>
<% end %>

app/views/pics/edit.html.erb
<div class="container-fluid h-100">
    <div class="row">
        <div class="col-md-12 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading mt-2">
                <h1>Editar Pic</h1>
                </div>
                <div class="panel-body">
                    <div class="current_image">
                        <strong class="center">Cambiar</strong>
                        <%= image_tag @pic.image.url(:medium)%>
                    </div>
                    <%= render "form" %>
                </div>
            </div>
        </div>
    </div>
    
</div>

app/views/pics/index.html.erb
     <div class="col-md-12 mt-3">
            <div class="transitions-enabled" id="pics">
                <% @pics.each do |pic| %>
                    <div class="box panel panel-default mt-3">
                        <%= link_to (image_tag pic.image.url), pic %>
                        <h2><%= link_to pic.title, pic %></h2>
                    </div>       
                <% end %>
            </div>
        </div>

app/views/pics/new.html.erb
<div class="container-fluid h-100">
    <div class="row">
        <div class="col-md-12 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading mt-2">
                <h1>Nueva Pic</h1>
                </div>
                <div class="panel-body">
                    <%= render "form" %>
                </div>
            </div>
        </div>
    </div>
    
</div>

app/views/pics/show.html.erb
<div class="container">
    <div class="row" id="pic_show">
        <div class="col-md-6 offset-md-3 mt-3">
            <div class="panel panel-default">
                <div class="panel heading pic_image">

                    <%= image_tag @pic.image.url(:medium) %>
                </div>
                <div class="panel-body">
                    <h1><%= @pic.title %></h1>
                    <p><%= @pic.description %></p>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="user">Por: <%= @pic.user.email %></p>
                        </div>
                        <div class="col-md-6">
                            <div class="btn-group pull-right">
                                <%= link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do %>
                                    <span class="fa fa-heart"></span>
                                    <%= @pic.get_upvotes.size %>
                                <% end %>
                                <% if user_signed_in? %>
                                    <%= link_to "Editar", edit_pic_path, class: "ml-3 btn btn-info"%>
                                    <%= link_to "Eliminar", pic_path(@pic), method: :delete, data: {confirm: "Estas Seguro" }, class: "ml-3 btn btn-danger" %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

           
        </div>
    </div>
</div>